apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator
spec:
  channel: piplines-1.16
  installPlanApproval: Automatic
  name: openshift-pipelines-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
